apiVersion: v1
kind: ReplicationController
metadata:
  name: {{.Name}}
  labels:
    group: load
spec:
  replicas: {{RandIntRange .ReplicasMin .ReplicasMax}}
  selector:
    name: {{.Name}}
  template:
    metadata:
      labels:
        name: {{.Name}}
        svc: {{.SvcName}}-{{DivideInt .Index 2}}
    spec:
      containers:
#      - image: k8s.gcr.io/pause:3.1
      - image: 	hub.kce.ksyun.com/ksyun/pause:3.1
        name: {{.Name}}
        resources:
          requests:
            cpu: 10m
            memory: "10M"
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
