# ASSUMPTIONS:
# - Underlying cluster should have 100+ nodes.
# - Number of nodes should be divisible by NODES_PER_NAMESPACE (default 100).

#Constants
  {{$NODE_MODE := DefaultParam .NODE_MODE "allnodes"}}
  {{$NODES_PER_NAMESPACE := DefaultParam .NODES_PER_NAMESPACE 100}}
  {{$PODS_PER_NODE := DefaultParam .PODS_PER_NODE 30}}
  {{$TEST_THROUGHPUT := DefaultParam .TEST_THROUGHPUT 10}}
  {{$BIG_GROUP_SIZE := 250}}
  {{$MEDIUM_GROUP_SIZE := 30}}
  {{$SMALL_GROUP_SIZE := 5}}
  {{$ENABLE_CHAOSMONKEY := DefaultParam .ENABLE_CHAOSMONKEY false}}

  #Variables
  {{$namespaces := DivideInt .Nodes $NODES_PER_NAMESPACE}}
  {{$totalPods := MultiplyInt $namespaces $NODES_PER_NAMESPACE $PODS_PER_NODE}}
  {{$saturationTime := DivideInt $totalPods $TEST_THROUGHPUT}}
  # bigRCs - 1/4 of namespace pods should be in big RCs.
  {{$bigRcsPerNamespace := DivideInt (MultiplyInt $NODES_PER_NAMESPACE $PODS_PER_NODE) (MultiplyInt 4 $BIG_GROUP_SIZE)}}
  # mediumRCs - 1/4 of namespace pods should be in medium RCs.
  {{$mediumRcsPerNamespace := DivideInt (MultiplyInt $NODES_PER_NAMESPACE $PODS_PER_NODE) (MultiplyInt 4 $MEDIUM_GROUP_SIZE)}}
  # smallRCs - 1/2 of namespace pods should be in small RCs.
  {{$smallRcsPerNamespace := DivideInt (MultiplyInt $NODES_PER_NAMESPACE $PODS_PER_NODE) (MultiplyInt 2 $SMALL_GROUP_SIZE)}}


name: qps
automanagedNamespaces: {{$namespaces}}
tuningSets:
  - name: QPS
    qpsLoad:
      qps: 100
steps:
  - measurements:
      - Identifier: APIResponsiveness
        Method: APIResponsiveness
        Params:
          action: reset
      - Identifier: TestMetrics
        Method: TestMetrics
        Params:
          action: start
          nodeMode: {{$NODE_MODE}}
  # Create SVCs
  - phases:
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: {{DivideInt (AddInt $bigRcsPerNamespace 1) 2}}
      tuningSet: QPS
      objectBundle:
      - basename: big-service
        objectTemplatePath: service.yaml
  - name: Creating SVCs

  # Delete SVCs
  - phases:
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 0
      tuningSet: QPS
      objectBundle:
      - basename: big-service
        objectTemplatePath: service.yaml
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 0
      tuningSet: Sequence
      objectBundle:
      - basename: medium-service
        objectTemplatePath: service.yaml
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 0
      tuningSet: Sequence
      objectBundle:
      - basename: small-service
        objectTemplatePath: service.yaml
  - name: Deleting SVCs
   Collect measurements
  - measurements:
      - Identifier: APIResponsiveness
        Method: APIResponsiveness
        Params:
          action: gather
      - Identifier: TestMetrics
        Method: TestMetrics
        Params:
          action: gather
